### ISSUE TITLE
Connection refused to port 1883

### ISSUE THREAD

**Issue by Goldwin** [erlio/vernemq#48]
Hi, 
I installed vernemq recently.
I installed it on one machine (let's called it broker01), and then run it.
When I try to connect to port 1883 locally from that machine, everything seems normal.
But when I try to connect from another machine, I just got the error message : 

Unable to connect to server (32103) - java.net.ConnectException: Connection refused
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)

I'm sure that I turn off the firewall.
FYI, after I experienced this, I installed mosquitto on broker01 and then try the same thing as I did before, and it works. 

Is there anything that I can do to make it works?

Thank you

**Comment by dergraf** [comment]
Hi there,

have you changed the default listener configuration? This is necessary if you're connecting from outside localhost.

e.g. to reach it from within the LAN
``listener.tcp.default = 192.168.10.10``

**Comment by Goldwin** [comment]
Ah,  I see. now it works 
Thank you  :+1:
